/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SUNARI
 */
public class Frame extends javax.swing.JFrame {
    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Bilangan1 = new javax.swing.JTextField();
        Bilangan2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Hasil = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        hasilbagi = new javax.swing.JButton();
        hasilkali = new javax.swing.JButton();
        hasiltambah = new javax.swing.JButton();
        hasilkurang = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Kalkulator Sederhana");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 30, 150, 14);

        jLabel2.setText("Bilangan 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 80, 60, 14);
        getContentPane().add(Bilangan1);
        Bilangan1.setBounds(140, 80, 160, 20);
        getContentPane().add(Bilangan2);
        Bilangan2.setBounds(140, 110, 160, 20);

        jLabel3.setText("Bilangan 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 110, 60, 14);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(null);

        Hasil.setEditable(false);
        Hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilActionPerformed(evt);
            }
        });
        jPanel2.add(Hasil);
        Hasil.setBounds(180, 240, 70, 40);

        jLabel4.setText("Hasil");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(200, 220, 22, 14);

        hasilbagi.setText(":");
        hasilbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilbagiActionPerformed(evt);
            }
        });
        jPanel2.add(hasilbagi);
        hasilbagi.setBounds(150, 160, 37, 23);

        hasilkali.setText("X");
        hasilkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilkaliActionPerformed(evt);
            }
        });
        jPanel2.add(hasilkali);
        hasilkali.setBounds(80, 160, 39, 23);

        hasiltambah.setText("+");
        hasiltambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasiltambahActionPerformed(evt);
            }
        });
        jPanel2.add(hasiltambah);
        hasiltambah.setBounds(220, 160, 41, 23);

        hasilkurang.setText("-");
        hasilkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilkurangActionPerformed(evt);
            }
        });
        jPanel2.add(hasilkurang);
        hasilkurang.setBounds(290, 160, 37, 23);

        jLabel5.setText("Operator");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(190, 144, 60, 10);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(-10, 0, 410, 300);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void hasilkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilkaliActionPerformed
    int bil1 = Integer.parseInt(Bilangan1.getText());
    int bil2 = Integer.parseInt(Bilangan2.getText());
    
    int hasilkali = bil1*bil2;
    
    Hasil.setText(String.valueOf(hasilkali));
    }//GEN-LAST:event_hasilkaliActionPerformed

    private void HasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilActionPerformed
    
    }//GEN-LAST:event_HasilActionPerformed

    private void hasilbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilbagiActionPerformed
    Float bil1 = Float.valueOf(Bilangan1.getText());
    Float bil2 = Float.valueOf(Bilangan2.getText());
    
    Float hasilbagi = bil1/bil2;
    
    Hasil.setText(String.valueOf(hasilbagi));
    }//GEN-LAST:event_hasilbagiActionPerformed

    private void hasiltambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasiltambahActionPerformed
    int bil1 = Integer.parseInt(Bilangan1.getText());
    int bil2 = Integer.parseInt(Bilangan2.getText());
    
    int hasiltambah = bil1+bil2;
    
    Hasil.setText(String.valueOf(hasiltambah));
    }//GEN-LAST:event_hasiltambahActionPerformed

    private void hasilkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilkurangActionPerformed
    int bil1 = Integer.parseInt(Bilangan1.getText());
    int bil2 = Integer.parseInt(Bilangan2.getText());
    
    int hasilkurang = bil1-bil2;
    
    Hasil.setText(String.valueOf(hasilkurang));
    }//GEN-LAST:event_hasilkurangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bilangan1;
    private javax.swing.JTextField Bilangan2;
    private javax.swing.JTextField Hasil;
    private javax.swing.JButton hasilbagi;
    private javax.swing.JButton hasilkali;
    private javax.swing.JButton hasilkurang;
    private javax.swing.JButton hasiltambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
